language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
script:
  - "prove -lvr t"
notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
